DATA SEGMENT
STRING DB 'Zheng Kangze', 0DH, 0AH, '1734123', 0DH, 0AH, '$'
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA
BEGIN:
      MOV AX, DATA
      MOV DS, AX
      LEA DX, STRING
      MOV AH,09H
      INT 21H
      MOV AH, 4CH
      INT 21H
CODE ENDS
      END BEGIN