EXTRN DELAY:FAR

DATA SEGMENT
STRING DB 'HELLO WORLD! Zheng Kangze 17341213',0DH, 0AH, '$'
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA
MAIN PROC
BEGIN:
      MOV AX, DATA
      MOV DS, AX
      MOV CX, 3
      LEA DX, STRING
L:    MOV AH, 9H      
      INT 21H
      CALL FAR PTR DELAY
      LOOP L 
      MOV AH, 4CH
      INT 21H
MAIN ENDP

CODE ENDS
      END BEGIN
      